name: Ejecutar Asistente Automatizado

on:
  push:
    branches:
      - main

jobs:
  ejecutar-asistente:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Verificar secretos
      run: |
        echo "Verificando secretos..."
        for secret in OPENAI_API_KEY NGROK_AUTH_TOKEN TWILIO_ACCOUNT_SID TWILIO_AUTH_TOKEN TWILIO_WHATSAPP_NUMBER; do
          if [ -z "${{ secrets[$secret] }}" ]; then echo "Falta $secret"; exit 1; fi
        done
        echo "Todos los secretos están configurados."

    - name: Descargar e instalar ngrok
      run: |
        echo "Descargando e instalando ngrok..."
        curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
        echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list >/dev/null
        sudo apt update
        sudo apt install ngrok

    - name: Configurar ngrok
      run: |
        echo "Configurando ngrok..."
        ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
        nohup ngrok http 5000 &
        sleep 5
        export NGROK_URL=$(curl -s http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url')
        echo "URL pública de ngrok: $NGROK_URL"

    - name: Ejecutar Flask
      run: python app.py
