name: Ejecutar Asistente Automatizado

on:
  push:
    branches:
      - main

jobs:
  run-asistente:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Verificar secretos
      run: |
        echo "Verificando que los secretos están configurados..."
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}"
        echo "TWILIO_WHATSAPP_NUMBER=${{ secrets.TWILIO_WHATSAPP_NUMBER }}"
        echo "NGROK_AUTH_TOKEN=${{ secrets.NGROK_AUTH_TOKEN }}"

    - name: Instalar y configurar ngrok
      run: |
        echo "Autenticando ngrok con el token proporcionado..."
        ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
        echo "Iniciando ngrok..."
        nohup ngrok http 5000 &

    - name: Obtener URL pública de ngrok
      run: |
        echo "Obteniendo la URL pública de ngrok..."
        sleep 5
        export NGROK_URL=$(curl -s http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url')
        echo "URL pública de ngrok: $NGROK_URL"
        echo "NGROK_URL=$NGROK_URL" >> $GITHUB_ENV

    - name: Configurar variables de entorno
      run: |
        echo "Configurando archivo .env con las variables necesarias..."
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env
        echo "TWILIO_WHATSAPP_NUMBER=${{ secrets.TWILIO_WHATSAPP_NUMBER }}" >> .env
        echo "NGROK_URL=${NGROK_URL}" >> .env

    - name: Ejecutar Flask
      run: |
        echo "Iniciando Flask..."
        python app.py
