name: Ejecutar Asistente Automatizado

on:
  push:
    branches:
      - main

jobs:
  ejecutar:
    runs-on: ubuntu-latest

    steps:
    - name: Configurar el Repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Instalar Dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Configurar ngrok
      env:
        NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}
      run: |
        echo "Autenticando ngrok..."
        ngrok authtoken $NGROK_AUTHTOKEN
        echo "Autenticación completada."

    - name: Iniciar el Servidor Flask
      env:
        FLASK_APP: app.py
      run: |
        python app.py
