name: Ejecutar Asistente Automatizado

on:
  push:
    branches:
      - main

jobs:
  run-asistente:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verificar secretos
        run: |
          echo "Verificando claves..."
          if [ -z "${{ secrets.OPENAI_API_KEY }}" ]; then exit 1; fi
          if [ -z "${{ secrets.NGROK_AUTH_TOKEN }}" ]; then exit 1; fi
          if [ -z "${{ secrets.TWILIO_ACCOUNT_SID }}" ]; then exit 1; fi
          if [ -z "${{ secrets.TWILIO_AUTH_TOKEN }}" ]; then exit 1; fi

      - name: Instalar y configurar ngrok
        run: |
          ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
          nohup ngrok http 5000 &

      - name: Obtener URL pública de ngrok
        run: |
          sleep 10
          export NGROK_URL=$(curl -s http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          echo "NGROK_URL=$NGROK_URL" >> $GITHUB_ENV
          echo "URL pública de ngrok: $NGROK_URL"

      - name: Configurar variables de entorno
        run: |
          echo "Configurando archivo .env con las variables necesarias..."
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env
          echo "NGROK_URL=$NGROK_URL" >> .env

      - name: Ejecutar Flask
        run: python app.py
